//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leave_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Leaves = new HashSet<Leave>();
        }
    
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Available_Y_Leave { get; set; }
        public Nullable<int> Avilable_P_Leave { get; set; }
        public Nullable<int> Department { get; set; }
        public int Role { get; set; }
        public int Office { get; set; }
        public string Phone { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Office Office1 { get; set; }
        public virtual Role Role1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
    }
}
