//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leave_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int Leave_Id { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public string Reson { get; set; }
        public int Leave_State { get; set; }
        public int Employee_Id { get; set; }
        public int Leave_Type { get; set; }
        public string medicalInspectionImgPath { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Leave_Status Leave_Status { get; set; }
        public virtual Leave_Type Leave_Type1 { get; set; }
    }
}
